# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pfksochi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pfksochi
  pod 'AHKNavigationController'
  pod 'Moya'
  # Pods for Astrological
  pod "CenteredCollectionView"
  pod "LGButton"
  pod 'Kingfisher'

end
